케라스 함수 불러오기

In [19]:
from keras.models import Sequential
from keras.layers import Dense

필요한 라이브러리 불러오기

In [20]:
import numpy
import tensorflow as tf # 케라스를 구동하려면 텐서플로우 모듈이 있어야 한다.

In [21]:
# 실행할 때마다 같은 결과를 출력하기 위해 설정하는 부분

In [22]:

seed = 0
numpy.random.seed (seed)
tf.set_random_seed(seed)

In [23]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 9E3C-600B

 C:\Users\dindi\str\모두의 딥러닝 디렉터리

2020-01-16  오전 11:06    <DIR>          .
2020-01-16  오전 11:06    <DIR>          ..
2020-01-15  오후 04:09    <DIR>          .ipynb_checkpoints
2020-01-12  오전 06:04    <DIR>          교재소스코드
2020-01-15  오후 04:14             3,246 선형 회귀 실습2_p61_200115.ipynb
2020-01-15  오후 04:27             5,938 선형 회귀 실습_p52_200115.ipynb
2020-01-16  오전 11:06            14,419 폐암 수술 환자의 생존율 예측하기_p29_200112.ipynb
               3개 파일              23,603 바이트
               4개 디렉터리  41,365,422,080 바이트 남음


In [24]:
import numpy as np

## seed(임의의 숫자)

In [25]:
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [26]:
np.random.rand(10)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [27]:
np.random.rand(0)

array([], dtype=float64)

In [28]:
seed=0
np.random.seed(seed)

In [29]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [30]:
np.random.rand(5)# 5개 임의로 불러줌

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [31]:
seed=0 # seed값을 한 셀안에 넣어주어야 같은 값이 나옴
np.random.seed(seed)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [32]:
seed=0 # seed값을 한 셀안에 넣어주어야 같은 값이 나옴
np.random.seed(seed)
np.random.rand(5) # 1차원 배열의 형태로 나옴

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [34]:
# 5까지 아무거나
np.random.randint(6)
# 1부터 19까지 아무거나
np.random.randint(1,20)
#0부터 9까지 숫자 중 아무 숫자나 2행 3열의 형태로 보여달라
# np.random.randint(10, size(2,3))
# 10부터 19까지 숫자 중 아무 숫자나 3행 5열의 형태로 보여달라

7

In [35]:
# 난수와 비슷하지만 시드 값에 따라 항상 같은 결과를 반환
np.random.seed(76923) # 임의의 정수값을 준다. 보통은 0으로 준다.

a = np.random.random((2,2))# 2행 2열의 형태로 나타남
b = np.random.sample((2,2))
c = np.random.randint(1,3,(2,2), dtype=int)

print(a)
print()
print(b)
print()
print(c)


[[0.76367992 0.87641303]
 [0.53095238 0.38451373]]

[[0.2777934  0.05650517]
 [0.44143693 0.7142663 ]]

[[1 1]
 [2 1]]


In [36]:
# 난수와 비슷하지만 시드 값에 따라 항상 같은 결과를 반환
np.random.seed(76923) # 임의의 정수값을 준다. 보통은 0으로 준다.

a = np.random.random((2,2))
b = np.random.sample((2,2))
c = np.random.randint(1,3,(2,2), dtype=int)

print(a)
print()
print(b)
print()
print(c)

[[0.76367992 0.87641303]
 [0.53095238 0.38451373]]

[[0.2777934  0.05650517]
 [0.44143693 0.7142663 ]]

[[1 1]
 [2 1]]


In [37]:
#0부터 4까지의 데이터를 석어서 나옴
np.random.choice(5,5, replace=False) # shuffle 명령과 같다

array([0, 2, 1, 3, 4])

In [38]:
# 준비된 수술 환자 데이터를 불러들인다.
Data_set = numpy.loadtxt('./교재소스코드/dataset/ThoraricSurgery.csv',delimiter=",")


In [39]:
# 환자의 기록과 수술 결과를 x와 Y로 구분하여 저장
X = Data_set[:,0:17]# 속성 : 환자에 대한 17개 항목에 대한 정보
Y = Data_set[:,17] # 클래스: 환자수술결과

In [40]:
# 딥러닝 구조를 결정(모델을 설정하고 실행하는 부분)

model = Sequential()# 딥러닝 구조를 순차적으로 한층한층 쌓아올림
model.add(Dense(30, input_dim=17,activation='relu')) # 0~17개의 데이터를 넣고 30개(결과)가 나옴 # add:추가 Dense는 층이다. 맨마지막: 출력층(맨위 위치) 맨 처음: 입력층(맨마지막 위치)
model.add(Dense(1,activation='sigmoid')) # 30개를 통해서 나온 개수가 1 (분류:살아있다)

In [41]:
# 딥러닝을 실행
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])
model.fit(X,Y, epochs=30, batch_size=10) # epochs: 반복의 수 300개의 데이터를 10묶어서 30번 반복해서 돌림

# 결과를 출력
print("\n Accuracy: %.4f" % (model.evaluate(X,Y)[1]))


Epoch 1/30
470/470 [==============================] - 0s 481us/step - loss: 0.8285 - accuracy: 0.1617
Epoch 2/30
470/470 [==============================] - 0s 153us/step - loss: 0.2251 - accuracy: 0.7617
Epoch 3/30
470/470 [==============================] - 0s 155us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 4/30
470/470 [==============================] - 0s 162us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 5/30
470/470 [==============================] - 0s 172us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 6/30
470/470 [==============================] - 0s 170us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 7/30
470/470 [==============================] - 0s 162us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 8/30
470/470 [==============================] - 0s 176us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 9/30
470/470 [==============================] - 0s 168us/step - loss: 0.1489 - accuracy: 0.8511
Epoch 10/30
470/470 [==============================] - 0s 170us/step - loss: 0.14